name: aws_lambda
description: A flutter plugin made to allow the usage of aws lambdas via each platform's native aws lambda plugin.
version: 0.0.1
author: Nico Feulner

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: de.nico.aws_lambda
        pluginClass: AWSLambdaPlugin